name: gdmicro
channels:
  - pytorch
  - conda-forge
  - r
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - bioconductor-biobase=2.46.0
  - bioconductor-biocgenerics=0.32.0
  - bioconductor-biomformat=1.14.0
  - bioconductor-biostrings=2.54.0
  - bioconductor-iranges=2.20.0
  - bioconductor-multtest=2.42.0
  - bioconductor-phyloseq=1.30.0
  - bioconductor-rhdf5=2.30.0
  - bioconductor-rhdf5lib=1.8.0
  - bioconductor-s4vectors=0.24.0
  - bioconductor-siamcat=1.6.0
  - bioconductor-xvector=0.26.0
  - bioconductor-zlibbioc=1.32.0
  - blas=1.0
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - cairo=1.16.0
  - certifi=2022.9.24
  - cffi=1.14.4
  - charset-normalizer=2.1.1
  - colorama=0.4.5
  - conda=4.12.0
  - conda-package-handling=1.9.0
  - cryptography=38.0.2
  - cudatoolkit=10.2.89
  - curl=7.68.0
  - cycler=0.11.0
  - dbus=1.13.6
  - decorator=5.1.1
  - expat=2.4.9
  - ffmpeg=4.3
  - fontconfig=2.14.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - gcc_impl_linux-64=7.5.0
  - gcc_linux-64=7.5.0
  - gettext=0.21.1
  - gfortran_impl_linux-64=7.5.0
  - gfortran_linux-64=7.5.0
  - glib=2.66.3
  - gmp=6.2.1
  - gnutls=3.6.13
  - graphite2=1.3.13
  - gsl=2.5
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - gxx_impl_linux-64=7.5.0
  - gxx_linux-64=7.5.0
  - harfbuzz=2.4.0
  - icu=64.2
  - idna=3.4
  - intel-openmp=2022.1.0
  - jpeg=9e
  - kernel-headers_linux-64=2.6.32
  - kiwisolver=1.4.4
  - krb5=1.16.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=9.0.1
  - libcurl=7.68.0
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-ng=12.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.66.3
  - libgomp=12.1.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm9=9.0.1
  - libopenblas=0.3.12
  - libpng=1.6.38
  - libsolv=0.7.22
  - libsqlite=3.39.4
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - libzlib=1.2.12
  - make=4.3
  - matplotlib=3.1.2
  - matplotlib-base=3.1.2
  - mkl=2022.1.0
  - ncurses=6.3
  - nettle=3.6
  - networkx=2.4
  - nspr=4.32
  - nss=3.78
  - numpy=1.17.3
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=1.1.1q
  - pandas=1.0.1
  - pandoc=2.19.2
  - pango=1.42.4
  - pcre=8.45
  - pillow=9.2.0
  - pip=22.2.2
  - pixman=0.38.0
  - pthread-stubs=0.4
  - pycosat=0.6.3
  - pycparser=2.21
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pyqt=5.12.3
  - pysocks=1.7.1
  - python=3.7.3
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytorch=1.12.0
  - pytorch-mutex=1.0
  - pytz=2022.4
  - qt=5.12.5
  - r-ade4=1.7_16
  - r-ape=5.5
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.2.1
  - r-base=3.6.1
  - r-base64enc=0.1_3
  - r-bbmisc=1.11
  - r-beanplot=1.2
  - r-blob=1.2.1
  - r-brio=1.1.2
  - r-broom=0.7.6
  - r-callr=3.7.0
  - r-cellranger=1.1.0
  - r-checkmate=2.0.0
  - r-cli=2.5.0
  - r-clipr=0.7.1
  - r-cluster=2.1.0
  - r-codetools=0.2_18
  - r-colorspace=2.0_1
  - r-corrplot=0.88
  - r-cpp11=0.2.7
  - r-crayon=1.4.1
  - r-curl=4.3.1
  - r-data.table=1.14.0
  - r-dbi=1.1.1
  - r-dbplyr=2.1.1
  - r-desc=1.3.0
  - r-diffobj=0.3.4
  - r-digest=0.6.27
  - r-dplyr=1.0.6
  - r-ellipsis=0.3.2
  - r-evaluate=0.14
  - r-fansi=0.4.2
  - r-farver=2.1.0
  - r-fastmatch=1.1_0
  - r-forcats=0.5.1
  - r-foreach=1.5.1
  - r-fs=1.5.0
  - r-generics=0.1.0
  - r-ggplot2=3.3.3
  - r-glmnet=4.0_2
  - r-glue=1.4.2
  - r-gridbase=0.4_7
  - r-gridextra=2.3
  - r-gtable=0.3.0
  - r-haven=2.4.1
  - r-highr=0.9
  - r-hms=1.1.0
  - r-htmltools=0.5.1.1
  - r-httr=1.4.2
  - r-igraph=1.2.6
  - r-infotheo=1.2.0
  - r-isoband=0.2.4
  - r-iterators=1.0.13
  - r-jsonlite=1.7.2
  - r-knitr=1.33
  - r-labeling=0.4.2
  - r-lattice=0.20_44
  - r-liblinear=2.10_12
  - r-lifecycle=1.0.0
  - r-lubridate=1.7.10
  - r-magrittr=2.0.1
  - r-markdown=1.1
  - r-mass=7.3_54
  - r-matrix=1.3_3
  - r-matrixstats=0.58.0
  - r-mgcv=1.8_35
  - r-mime=0.10
  - r-mlr=2.19.0
  - r-modelr=0.1.8
  - r-munsell=0.5.0
  - r-nlme=3.1_150
  - r-openssl=1.4.4
  - r-parallelmap=1.5.0
  - r-paramhelpers=1.14
  - r-permute=0.9_5
  - r-pillar=1.6.1
  - r-pixmap=0.4_12
  - r-pkgconfig=2.0.3
  - r-pkgload=1.2.1
  - r-plyr=1.8.6
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-proc=1.17.0.1
  - r-processx=3.5.2
  - r-progress=1.2.2
  - r-prroc=1.3.1
  - r-ps=1.6.0
  - r-purrr=0.3.4
  - r-r6=2.5.0
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.6
  - r-readr=1.4.0
  - r-readxl=1.3.1
  - r-rematch=1.0.1
  - r-rematch2=2.1.2
  - r-reprex=2.0.0
  - r-reshape2=1.4.4
  - r-rlang=0.4.11
  - r-rmarkdown=2.8
  - r-rprojroot=2.0.2
  - r-rstudioapi=0.13
  - r-rvest=1.0.0
  - r-scales=1.1.1
  - r-selectr=0.4_2
  - r-shape=1.4.6
  - r-sp=1.4_5
  - r-stringi=1.4.6
  - r-stringr=1.4.0
  - r-survival=3.2_11
  - r-sys=3.4
  - r-testthat=3.0.2
  - r-tibble=3.1.2
  - r-tidyr=1.1.3
  - r-tidyselect=1.1.1
  - r-tidyverse=1.2.1
  - r-tinytex=0.31
  - r-utf8=1.2.1
  - r-vctrs=0.3.8
  - r-vegan=2.5_6
  - r-viridislite=0.4.0
  - r-waldo=0.2.5
  - r-withr=2.4.2
  - r-xfun=0.23
  - r-xml=3.99_0.3
  - r-xml2=1.3.2
  - r-yaml=2.2.1
  - readline=8.1.2
  - requests=2.28.1
  - ruamel_yaml=0.15.80
  - scipy=1.5.2
  - sed=4.8
  - setuptools=59.8.0
  - six=1.16.0
  - sqlite=3.39.4
  - sysroot_linux-64=2.12
  - tk=8.6.12
  - tktable=2.10
  - torchaudio=0.12.0
  - torchvision=0.13.0
  - tornado=6.2
  - tqdm=4.64.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - urllib3=1.26.11
  - wheel=0.37.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - args==0.1.0
    - backcall==0.2.0
    - clint==0.5.1
    - coverage==6.5.0
    - hiddenlayer==0.3
    - higra==0.6.4
    - ipython==7.32.0
    - jedi==0.18.1
    - joblib==1.2.0
    - mamba==0.11.2
    - matplotlib-inline==0.1.6
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.31
    - ptyprocess==0.7.0
    - pygments==2.13.0
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - scikit-learn==1.0.2
    - threadpoolctl==3.1.0
    - traitlets==5.4.0
    - wcwidth==0.2.5
